### ISSUE TITLE
gamenet: Publish to crates.io

### ISSUE THREAD

**Issue by Zwelf** [heinrich5991/libtw2#53]
It would be helpful to me if you could upload the gamenet crates to crates.io to ease including them (not urgent, because there is a way to specify git dependencies in Cargo.toml, but would be nice to have).

These are my current dependencies to this repository:

```toml
gamenet_ddnet = { git = "https://github.com/heinrich5991/libtw2" }
gamenet_teeworlds_0_7 = { git = "https://github.com/heinrich5991/libtw2" }
packer = { git = "https://github.com/heinrich5991/libtw2" }
```
